apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-sapper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-sapper
  template:
    metadata:
      labels:
        app: portfolio-sapper
    spec:
      containers:
        - name: portfolio
          image: jonesrussell/portfolio-app:1.0.0
          env:
          - name: BLOG_URL
            value: "https://blog.jonesrussell42.xyz/feed.json"
          - name: BELL_CREEK_URL 
            value: "https://bell-creek.jonesrussell42.xyz"
          ports:
            - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: portfolio-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - www.jonesrussell42.xyz
      secretName: portfolio-tls
  rules:
    - host: www.jonesrussell42.xyz
      http:
        paths:
          - backend:
              serviceName: portfolio-sapper
              servicePort: 3000 
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Email address used for ACME registration
    email: jonesrussell42@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: letsencrypt-prod-private-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-sapper
spec:
  selector:
    app: portfolio-sapper
  ports:
    - protocol: TCP
      port: 3000
  type: ClusterIP

